# Generated by Django 4.2.4 on 2024-08-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField(unique=True)),
                ('summary', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('published', models.DateTimeField()),
            ],
        ),
    ]
