# Generated by Django 4.2.4 on 2024-08-16 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_category_website'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Website',
        ),
    ]
