# Generated by Django 4.2.4 on 2024-08-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_bookmark'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set(),
        ),
    ]
